development:
  adapter: mysql
  database: sh800
  encoding: utf8
  pool: 5
  username: sh800
  password: sh800
  timeout: 5000
  host: localhost

production:
  adapter: mysql
  database: sh800
  encoding: utf8
  pool: 5
  username: sh800
  password: sh800
  timeout: 5000
  host: localhost